<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\DataAccess\DataAccess.csproj">
		  <PrivateAssets>All</PrivateAssets> 
	  </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ManagerServices\Abstracts\" />
    <Folder Include="ManagerServices\Concretes\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="8.1.0" />
  </ItemGroup>
	<!--<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>-->
</Project>
