<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\DataAccess\DataAccess.csproj">
		  <PrivateAssets>All</PrivateAssets> 
	  </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ManagerServices\Abstracts\" />
    <Folder Include="ManagerServices\Concretes\" />
  </ItemGroup>

</Project>
